mysite2/analysis_material/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.HomeViews.as_view(), name="home"),    # главная страница
    path('calculation_compatibility/', views.AnalysisMaterialViews.as_view(), name="calculation_compatibility"),
    path('result_analize_two/', views.result_analize_two, name="result_analize_two"),
    path('result_analize_one/', views.result_analize_one, name="result_analize_one"),
    path('personal_account/', views.PersonalAccountViews.as_view(), name="personal_account"),
    path('<int:pk>/', views.DocumentDetailViews.as_view(), name="document_detail"),
    path('delete/<int:pk>/', views.DocumentDeleteView.as_view(), name='document_delete'),
    #path('delete/<int:pk>/', views.deleteDocument, name='deleteDocument'),
    path('new/', views.DocumentCreateView.as_view(), name='document_new'), # new
]

mysite2/mysite2/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('analysis_material.urls')),
    path('accounts/', include('allauth.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite2/analysis_material/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

class Document(models.Model):
    user = models.ForeignKey(User, verbose_name="Пользователь", on_delete=models.SET_NULL, null=True, blank=True)
    name_document = models.CharField("Учебный материал", max_length=200)
    path_file = models.FileField("Файл", upload_to='documents/')
    uploaded_at = models.DateTimeField("Время загрузки", auto_now_add=True)

    def __str__(self):
        return self.name_document

    def get_absolute_url(self):
        return reverse("document_detail", kwargs={"pk": self.pk})

    class Meta:
        verbose_name = "Учебный материал"
        verbose_name_plural = "Учебные материалы"

class AnalysisDocument(models.Model):
    compatibility_document = models.FloatField(default=0)

    def __str__(self):
        return self.compatibility_document

class Relation_Document_Analysis(models.Model):
    document = models.ForeignKey(Document, on_delete=models.CASCADE)
    analysis_document = models.ForeignKey(AnalysisDocument, on_delete=models.CASCADE)

class Keyword(models.Model):
    document = models.ForeignKey(Document, on_delete=models.CASCADE)
    description_keyword = models.CharField(max_length=100)
    periodicity_keyword = models.IntegerField(default=0)

mysite2/analysis_material/forms.py
from django import forms

from .models import Document

class DocumentForm(forms.ModelForm):
    class Meta:
        model = Document
        fields = ['name_document', 'path_file']

mysite2/analysis_material/views.py
from django.shortcuts import render, redirect
from django.views.generic import View, ListView, DetailView, CreateView, DeleteView
from analyzer.analyzer_class.read_file import ReadFile
from analyzer.analyzer_class.compatibility_analysis import CompatibilityAnalysis
from analyzer.analyzer_class.thesaurus import Thesaurus
from .models import Document, User
from django.urls import reverse_lazy
from .forms import DocumentForm

class HomeViews(View):
    """ Главная страница """
    def get(self, request):
        return render(request, "analysis_material/home.html")

class AnalysisMaterialViews(View):
    """ Страница для расчёта совместимости """
    def get(self, request):
        return render(request, "analysis_material/calculation_compatibility.html")

class PersonalAccountViews(ListView):
    """ Личный кабинет: список документов, список анализов """
    model = Document
    template_name = "analysis_material/personal_account.html"
    paginate_by = 10

    def get_queryset(self):
        return Document.objects.filter(user=self.request.user)

class DocumentDetailViews(DetailView):
    """ Подробная информация о документе """
    model = Document
    template_name = 'analysis_material/document_detail.html'

class DocumentDeleteView(DeleteView):
    """ Удаление документа """
    model = Document
    template_name = 'analysis_material/personal_account.html'
    success_url = reverse_lazy('personal_account')

class DocumentCreateView(CreateView):
    """ Добавление документа """
    model = Document
    form_class = DocumentForm
    template_name = 'analysis_material/document_form.html'


    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(DocumentCreateView, self).form_valid(form)

def result_analize_one(request):
    # проверка чтобы либо текст либо файл
    # если файл не того формата тоже првоерка
    name_document = ""
    one_text_area = ""
    path_file = None
    read_file = ReadFile()

    if 'name_document' in request.POST and request.POST['name_document']:
        name_document = request.POST['name_document']
    if 'one_text_area' in request.POST and request.POST['one_text_area']:
        one_text_area = request.POST['one_text_area']
    if 'path_file' in request.FILES and request.FILES['path_file']:
        path_file = request.FILES['path_file']
        path_file = read_file(path_file)

    thesaurus = Thesaurus()
    keys, tfidf = thesaurus(path_file)
    return render(request,
                  'analysis_material/results_one.html', context={'name_document': name_document,
                                                    'keys': keys,
                                                    'tfidf': tfidf})
def result_analize_two(request):
    # проверка чтобы либо текст либо файл
    # если файл не того формата тоже првоерка
    one_material_name = ""
    two_material_name = ""
    one_text_area = ""
    two_text_area = ""
    one_uploaded_file = None
    two_uploaded_file = None
    read_file = ReadFile()

    if 'one_material_name' in request.POST and request.POST['one_material_name']:
        one_material_name = request.POST['one_material_name']
    if 'one_text_area' in request.POST and request.POST['one_text_area']:
        one_text_area = request.POST['one_text_area']
    if 'one_uploaded_file' in request.FILES and request.FILES['one_uploaded_file']:
        one_uploaded_file = request.FILES['one_uploaded_file']
        one_uploaded_file = read_file(one_uploaded_file)

    if 'two_material_name' in request.POST and request.POST['two_material_name']:
        two_material_name = request.POST['two_material_name']
    if 'two_text_area' in request.POST and request.POST['two_text_area']:
        two_text_area = request.POST['two_text_area']
    if 'two_uploaded_file' in request.FILES and request.FILES['two_uploaded_file']:
        two_uploaded_file = request.FILES['two_uploaded_file']
        two_uploaded_file = read_file(two_uploaded_file)

    compatibility_analysis = CompatibilityAnalysis()
    one_data, two_data, result = compatibility_analysis(one_text_area, two_text_area,
                                                                   one_uploaded_file, two_uploaded_file)
    return render(request,
                  'analysis_material/results_two.html', context={'one_material_name': one_material_name,
                                                    'two_material_name': two_material_name,
                                                    'one_data': one_data,
                                                    'two_data': two_data,
                                                    'result': result})

mysite2/templates/analysis_material/analize_two.html
{% extends "base.html" %}
{% block content %}

<section class="ftco-section ftco-no-pt">
    <form method="post" action="/result_analize_two" enctype ="multipart/form-data" class="search-property" >
        <div class="container">
            <div class="row">
                <div class="text pb-4 pt-5">
                    <h1 class="mb-4">Анализ двух материалов</h1>
                    <div class="desc">
                        <p>Данный анализ покажет насколько совпадают тезарусы данных материалов.</p>
                        <p>Для добавления материалов введите название и текст в соответствующие поля ниже.</p>
                        <p>Для проведения анализа нажмите на кнопку "Выполнить анализ" в самом низу страницы.</p>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="heading-section mb-4 ml-md-4 pl-md-5">
                        <h3 class="mb-4">
                            Первый материал для анализа
                        </h3>
                        <div class="row">
                            <div class="col-md-12 align-items-end ftco-animate">
                                <div class="form-group">
                                    <label for="#">Название материала</label>
                                    <div class="form-field">
                                        <input type="text" class="form-control" placeholder="Введите название"
                                               name="one_material_name">
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-12 align-items-end ftco-animate">
                                <div class="form-group">
                                    <label for="#">Текст материала</label>
                                    <div class="form-field">
                                        <textarea class="form-control" placeholder="Введите текст"
                                                  name="one_text_for_analize"></textarea>
                                    </div>
                                    {% csrf_token %}
                                    <input type="file" class="form-control" name="one_uploaded_file"/>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 d-flex">
                    <div class="heading-section mb-4 ml-md-4 pl-md-5">
                        <h3 class="mb-4">
                            Второй материал для анализа
                        </h3>
                        <div class="row">
                            <div class="col-md-12 align-items-end ftco-animate">
                                <div class="form-group">
                                    <label for="#">Название материала</label>
                                    <div class="form-field">
                                        <input type="text" class="form-control" placeholder="Введите название"
                                               name="two_material_name">
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-12 align-items-end ftco-animate">
                                <div class="form-group">
                                    <label for="#">Текст материала</label>
                                    <div class="form-field">
                                        <textarea class="form-control" placeholder="Введите текст"
                                                  name="two_text_for_analize"></textarea>
                                    </div>
                                    {% csrf_token %}
                                    <input type="file" class="form-control" name="two_uploaded_file"/>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
                <div class="col-md-12">
                    <div class="col-md-12 align-self-end ftco-animate">
                        <div class="form-group">
                            <div class="form-field">
                                <input type="submit" value="Выполнить анализ"
                                       class="form-control btn btn-primary"/>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</section>


<!-- loader -->
<div id="ftco-loader" class="show fullscreen">
    <svg class="circular" width="48px" height="48px">
        <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/>
        <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
                stroke="#F96D00"/>
    </svg>
</div>

{% endblock %}

mysite2/templates/analysis_material/calculation_compatibility.html
{% extends "base.html" %}

{% block content %}


  <div class="jumbotron">
    <div class="container">
      <h1 class="display-3">Инструкция</h1>
      <p>Возможно, здесь стоит описать порядок действий для анализа.</p>
    </div>
  </div>

<form method="post" action="{% url 'result_analize_two' %}" enctype ="multipart/form-data" class="search-property" >
  <div class="container">
    <div class="row">


      <div class="col-sm-6">
        <div class="container border border-secondary rounded mycol-sm-6">
            {% csrf_token %}
            <div class="form-group">
              <label for="nameDocument"><h4>Введите название 1 учебного материала:</h4></label>
              <input type="text" class="form-control" id="nameDocument" name="one_material_name" required>
            </div>
            <div class="form-group" >
              <label for="exampleFormControlFile1">Прикрепите файл для анализа (dox, docx):</label>
              <input type="file" class="form-control-file" id="exampleFormControlFile1" name="one_uploaded_file">
            </div>
            <textarea class="form-control" id="exampleFormControlTextarea1" placeholder="Вставьте текст для анализа" rows="15" name="one_text_for_analize" ></textarea><br>
        </div>
      </div>
      <div class="col-sm-6 ">
        <div class="container border border-secondary rounded mycol-sm-6">
            <div class="form-group">
              <label for="nameDocument"><h4>Введите название 2 учебного материала:</h4></label>
              <input type="text" class="form-control" id="nameDocument" name="two_material_name" required>
            </div>
            <div class="form-group" >
              <label for="exampleFormControlFile1">Прикрепите файл для анализа (dox, docx):</label>
              <input type="file" class="form-control-file" id="exampleFormControlFile1" name="two_uploaded_file">
            </div>
            <textarea class="form-control" id="exampleFormControlTextarea1" placeholder="Вставьте текст для анализа" rows="15" name="one_text_for_analize" ></textarea><br>
        </div>
      </div>
      <div class="col-sm text-center">
        <input type="submit" value="Рассчитать совместимость" class="form-control btn btn-secondary btn-block"/>
      </div>
    </div>
  </div>
</form>

{% endblock %}

mysite2/templates/analysis_material/document_detail.html
{% extends "base.html" %}

{% block content %}
  {% load static %}
  <div class="container">
    <h1>{{document.name_document}}</h1>
    <div class="text-right">
      <form method="post" action="{% url 'document_delete' document.pk  %}">
        {% csrf_token %}
        <button type="submit">
              <img src="{% static 'analysis_material/images/delete.png' %}" width="30" height="30" class="d-inline-block align-top" alt="" loading="lazy">
         </button>
      </form>
    </div>
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">Ключевое слово</th>
          <th scope="col">Частота</th>
        </tr>
      </thead>
      <tbody>
        {% for keyword in document.keyword_set.all %}
          <tr>
            <td>{{keyword.description_keyword}}</td>
            <td>{{keyword.periodicity_keyword}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

{% endblock %}

mysite2/templates/analysis_material/document_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
  <h1>Добавление учебного материала:</h1>
  <form action="{% url 'result_analize_one' %}" method="post" enctype ="multipart/form-data">
    {% csrf_token %}

    {% if user.is_authenticated %}
    <div class="form-group">

        {{ form.name_document|as_crispy_field }}
    </div>
    {% endif %}
    <div class="form-group">
      <label for="exampleFormControlFile1">Прикрепите файл для анализа (dox, docx):</label>
        {{ form.path_file|as_crispy_field }}
    </div>
    <textarea class="form-control" id="exampleFormControlTextarea1" placeholder="Вставьте текст для анализа" rows="15" name="one_text_for_analize" ></textarea><br>
    <input type="submit" value="Добавить" class="form-control btn btn-secondary btn-block"/>
  </form>
</div>

{% endblock content %}

mysite2/templates/analysis_material/home.html
{% extends "base.html" %}

{% block content %}
  {% load static %}
  <div class="container text-center">
    <main role="main" class="inner cover">
      <h1 class="cover-heading">Анализ совместимости учебных материалов</h1>
      <p class="lead">Здесь должен быть какой-то красивый текст, описывающий функциональность этого сервиса!</p>
      <p class="lead">
        <a href="{% url 'calculation_compatibility' %}" class="btn btn-lg btn-secondary">Рассчитать совместимость</a>
      </p>
    </main>
  </div>

{% endblock %}

mysite2/templates/analysis_material/personal_account.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container">
    <h1>Пользователь: {{ user.get_username }}</h1>
    <ul class="nav nav-tabs" id="tab-example" role="tablist">
        <li class="nav-item">
            <a class="nav-link active" id="first-tab" data-toggle="tab"
               href="#first-tab-content" role="tab" aria-controls="first-tab-content"
               aria-selected="true">Загруженные файлы</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="second-tab" data-toggle="tab"
               href="#second-tab-content" role="tab" aria-controls="second-tab-content"
               aria-selected="false">Результаты анализа</a>
        </li>
    </ul>

    <div class="tab-content" id="tab-content-example">
        <div class="tab-pane fade show active" id="first-tab-content" role="tabpanel"
             aria-labelledby="first-tab">
             {% if document_list %}
             <div class="row">
               <div class="col-6 text-left">
                 <div class="input-group mb-3">
                    <div class="input-group-prepend">
                      <span class="input-group-text" id="inputGroup-sizing-default"><img src="{% static 'analysis_material/images/search.png' %}" width="23" height="23" class="d-inline-block align-top" alt="" loading="lazy">
                  </span>
                    </div>
                    <input type="text" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default">
                  </div>
               </div>
               <div class="col-6 text-right">
                 <button type="button" class="btn btn-info" id="add_doc">Добавить</button>
                 <button type="button" class="btn btn-secondary" id="delete_doc">Удалить</button>
               </div>
             </div>

               <div class="table-wrapper-scroll-y my-custom-scrollbar ">
                 <table class="table table-bordered table-striped table-hover display" id="example">
                   <thead class="thead-dark">
                     <tr>
                       <th scope="col"><input type="checkbox"></th>
                       <th scope="col">Наименование материала</th>
                       <th scope="col">Дата загрузки</th>
                     </tr>
                   </thead>
                   <tbody>
                     {% for document in document_list %}
                     <tr>
                       <th width="15px" scope="row" class="table-fragment"><input type="checkbox"></th>
                       <td><a href="{{ document.get_absolute_url }}">{{document.name_document}}</a></td>
                       <td>{{document.uploaded_at}}</td>
                     </tr>
                     {% endfor %}
                   </tbody>
                 </table>
                 <nav aria-label="Page navigation example">
                  <ul class="pagination justify-content-center">
                    <li class="page-item disabled">
                      <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Предыдущая</a>
                    </li>
                    <li class="page-item"><a class="page-link" href="#">1</a></li>
                    <li class="page-item"><a class="page-link" href="#" aria-disabled="true">2</a></li>
                    <li class="page-item"><a class="page-link" href="#" aria-disabled="true">3</a></li>
                    <li class="page-item">
                      <a class="page-link" href="#" aria-disabled="true">Следующая</a>
                    </li>
                  </ul>
                </nav>
               </div>
               <!--<p>Для загрузки файлов для анализа нажмите
               <a href="{% url 'document_new' %}">сюда.</a></p>-->
               {% else %}

                 <p>Для загрузки файлов для анализа нажмите
                 <a href="{% url 'document_new' %}">сюда.</a></p>
               {% endif %}
        </div>
        <div class="tab-pane fade" id="second-tab-content" role="tabpanel"
             aria-labelledby="second-tab">
             {% if document_list %}
             <div class="row">
               <div class="col-6 text-left">
                 <div class="input-group mb-3">
                    <div class="input-group-prepend">
                      <span class="input-group-text" id="inputGroup-sizing-default"><img src="{% static 'analysis_material/images/search.png' %}" width="23" height="23" class="d-inline-block align-top" alt="" loading="lazy">
                  </span>
                    </div>
                    <input type="text" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default">
                  </div>
               </div>
               <div class="col-6 text-right">
                 <button type="button" class="btn btn-info" id="add_analysis">Новый анализ</button>
                 <button type="button" class="btn btn-secondary" id="delete_analysis">Удалить</button>
               </div>
             </div>

             <div class="row">
               <div class="col">
                   <div class="input-group mb-3">
                      <div class="input-group-prepend">
                        <label class="input-group-text" for="inputGroupSelect01"><img src="{% static 'analysis_material/images/filter.png' %}" width="23" height="23" class="d-inline-block align-top" alt="" loading="lazy"></label>
                      </div>
                      <select class="custom-select" id="inputGroupSelect01">
                        <option selected>Выберите тип совместимости...</option>
                        <option value="1">Внутренняя</option>
                        <option value="2">Внешняя</option>
                        <option value="3">Все</option>
                      </select>
                    </div>
               </div>
             </div>

               <div class="table-wrapper-scroll-y my-custom-scrollbar">
                 <table class="table table-bordered table-striped table-hover">
                   <thead class="thead-dark">
                    <tr>
                      <th scope="col"><input type="checkbox"></th>
                      <th scope="col">Первый материал</th>
                      <th scope="col">Второй материал</th>
                      <th scope="col">Тип совместимости</th>
                      <th scope="col">Процент совместимости</th>
                      <th scope="col"></th>
                    </tr>
                   </thead>
                   <tbody>
                     {% for document in document_list %}
                     <tr>
                       <th width="15px" scope="row" class="table-fragment"><input type="checkbox"></th>
                       <td>{{document.name_document}}</td>
                       <td>{{document.name_document}}</td>
                       <td>Внешняя</td>
                       <td>7%</td>
                       <td><button class="btn btn-secondary btn-block" type="button">Подробнее</button></td>
                     </tr>
                     {% endfor %}
                   </tbody>
                 </table>
                 <nav aria-label="Page navigation example">
                  <ul class="pagination justify-content-center">
                    <li class="page-item disabled">
                      <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Предыдущая</a>
                    </li>
                    <li class="page-item"><a class="page-link" href="#">1</a></li>
                    <li class="page-item"><a class="page-link" href="#" aria-disabled="true">2</a></li>
                    <li class="page-item"><a class="page-link" href="#" aria-disabled="true">3</a></li>
                    <li class="page-item">
                      <a class="page-link" href="#" aria-disabled="true">Следующая</a>
                    </li>
                  </ul>
                </nav>
               </div>
               <!--<p>Для проведения анализа нажмите
               <a href="{% url 'calculation_compatibility' %}">сюда.</a></p>
               {% else %}
                 <p>Для проведения анализа нажмите
                 <a href="{% url 'calculation_compatibility' %}">сюда.</a></p>
               {% endif %}-->
        </div>
    </div>
</div>


{% endblock %}

mysite2/templates/analysis_material/results_one.html
{% include "base.html" %}
{% load static %}
{% block content %}


<div class="container">
  <h1>Результаты анализа</h1>
  <div class="row">
    <div class="col-6 text-left">
      <h4>Наименование материала: {{ name_document }}</h4>
    </div>
    <div class="col-6 text-right">
      <button type="button" class="btn btn-info" id="add_in_biblio">Добавить в библиотеку</button>
    </div>
  </div>

  <div class="row">
    <div class="col-4">
      <div class="input-group mb-3">
         <div class="input-group-prepend">
           <span class="input-group-text" id="inputGroup-sizing-default"><img src="{% static 'analysis_material/images/search.png' %}" width="23" height="23" class="d-inline-block align-top" alt="" loading="lazy">
       </span>
         </div>
         <input type="text" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default">
       </div>
      <div class="card">
        <div class="card-header">
          <h6>Слова</h6>
        </div>
        <div class="card-body">
          <div class="form-check">
            <input class="form-check-input" type="radio" name="exampleRadios" id="exampleRadios1" value="option1" checked>
            <label class="form-check-label" for="exampleRadios1">
              Предметный тезаурус
            </label>
          </div>
          <div class="form-check">
            <input class="form-check-input" type="radio" name="exampleRadios" id="exampleRadios1" value="option1" checked>
            <label class="form-check-label" for="exampleRadios1">
              Слова-кандидаты
            </label>
          </div>
          <div class="form-check">
            <input class="form-check-input" type="radio" name="exampleRadios" id="exampleRadios1" value="option1" checked>
            <label class="form-check-label" for="exampleRadios1">
              Все слова
            </label>
          </div>
        </div>
        <!--<div class="card-header">
          <h6>Сортировать</h6>
        </div>
        <div class="card-body">
          <input type="checkbox" name="option1" value="a1">  Алфавиту <Br>
          <input type="checkbox" name="option2" value="a2">  Значимости слова <Br>
          <input type="checkbox" name="option3" value="a3">  Частоте слова <Br>
        </div>-->
        <button type="button" class="btn btn-info" id="filtres">Показать</button>
      </div>
    </div>


    <div class="col-8">
      <form method="GET" action="{% url 'personal_account' %}" enctype ="multipart/form-data" class="search-property" >
        {% csrf_token %}

        <div class="table-wrapper-scroll-y my-custom-scrollbar">
          <table class="table table-bordered table-striped table-hover">
            <thead class="thead-dark">
              <tr>
                <th scope="row" class="table-fragment"><input type="checkbox" checked></th>
                <th scope="col">Слово</th>
              </tr>
            </thead>
            <tbody>
              {% for key in keys %}
              <tr>
                <th scope="row" class="table-fragment"><input type="checkbox" checked></th>
                <td>{{ key }}</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </form>
    </div>
  </div>


</div>

{% endblock  %}